### ISSUE TITLE
Help: How to delete these PVC and PV？

### ISSUE THREAD

**Issue by GuridMa** [openebs-archive/dynamic-nfs-provisioner#144]
![image](https://user-images.githubusercontent.com/74485252/188588025-b31cc017-cf13-4e51-9511-bf877a5f99e4.png)
Help: How to delete these PVC and PV？

PV and PVC is dynamic-nfs-provisioner create

**Comment by dsharma-dc** [comment]
@GuridMa I see that in the screenshot you have provided, there is a typo in the command - a missing whitespace when providing `-n openebs`
I'm not sure if that's indeed the reason, but that's the first I'd ask for to be corrected.

**Comment by niladrih** [comment]
Hi @GuridMa. It's been a while, but if you're still hitting this issue, here's a link to the solution: https://github.com/openebs/openebs/issues/3329

In your outputs above, I don't see the openebs-nfs-provisioner. Is this an issue related to the dynamic-nfs-provisioner?

**Comment by niladrih** [comment]
Closing this issue as it is a known issue, and a duplicate to openebs/openebs#3329.
