### ISSUE TITLE
how to config nfs-server

### ISSUE THREAD

**Issue by szshary** [openebs-archive/dynamic-nfs-provisioner#150]
nfs-subdir-external-provisioner example：
  nfs:
    server: 10.0.0.0
    path: /data/nfs/test

**Comment by dsharma-dc** [comment]
@szshary Could you please share more details if there is any issue you are facing?
Is it that you are unable to have nfs-server up and running with this provisioner?

**Comment by dsharma-dc** [comment]
I am going ahead closing this issue for now. Please feel free to reopen if still there is any issue related to this, and let us know the relevant details.
