### ISSUE TITLE
How to set the SYNC=true env variable for the nfs-server pods through dynamic-nfs-provisioner?

### ISSUE THREAD

**Issue by keskival** [openebs-archive/dynamic-nfs-provisioner#154]
**Describe the problem/challenge you have**

I need to set the exports mount option sync on, because otherwise hard reboots cause file system corruption. This is already supported by the Alpine nfs-server image, through an environment variable SYNC=true.

Existing documentation doesn't describe how it would be possible to give SYNC=true environment variable for the nfs-server deployments through dynamic-nfs-provisioner.

**Describe the solution you'd like**

Support for passing environment variables to nfs-servers, and documentation mention for the same.

**Anything else you would like to add:**

This is a really useful project and thanks for the great work!

**Vote on this issue!**

This is an invitation to the OpenEBS community to vote on issues.  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by keskival** [comment]
It would seem this PR would allow setting sync as a mountOption:
https://github.com/openebs/dynamic-nfs-provisioner/pull/142/files

**Comment by dsharma-dc** [comment]
We are now reviewing the PR #142, so will look at this requirement along with that.

**Comment by dsharma-dc** [comment]
`mountOptions` have been added to the helm chart. Please give it a try for `sync` mount option and see if that serves the purpose.

**Comment by dsharma-dc** [comment]
I am closing this issue now. Please feel free to revert back and reopen if any further issues encountered.
