### ISSUE TITLE
Installation dynamic-nfs-provisioner On GKE

### ISSUE THREAD

**Issue by sanke-t** [openebs-archive/dynamic-nfs-provisioner#156]
This is not really an issue, but I would really appreciate any insights on this. I am trying to install dynamic NFS provisioner on GKE to with backend storage class with provisioner pd.csi.storage.gke.io

Challenge here is meeting the pre-requisite of installation of nfs-common/nfs-util package on the node. Container OS does not have a package manager and does not allow any operations on the node.

Is there a workaround for this other than having ubuntu nodes on the cluster?

**Comment by dsharma-dc** [comment]
Not something I've faced as always had base image Ubuntu while setting up cluster.
@sanke-t May be GKE support could be helpful here.
@datacore-tilangovan Is this something you have experience with?

**Comment by dsharma-dc** [comment]
Closing this based on suggestion to check workaround for container OS on GKE with their support. Please get back and reopen in case any help specific to nfs provisioner is required.
