### ISSUE TITLE
Container fails to start with the dynamic nfs provisioner

### ISSUE THREAD

**Issue by tampler** [openebs-archive/dynamic-nfs-provisioner#16]
**Describe the bug:** A clear and concise description of what the bug is.
Any container fails to start, when using the nfs provisioner

**Expected behaviour:** A concise description of what you expected to happen
Container starts and nfs storage is provisioned

**Steps to reproduce the bug:**
1. `mkdir -p /mnt/data`
2. `sudo chown -R admin:admin /mnt/data`
3. `kubectl apply -f https://gist.github.com/tampler/44baacbd7606561a11cf949fa462cedd`
4. `kubectl get pvc` -> find the pvc created: `ebs-rwx-pvc                           Bound    pvc-505263e6-25d8-4b86-9362-b95ea79fa7fc   10Gi       RWX            openebs-rwx        32m`
5. `kubectl get pv` -> find the pv created: `pvc-505263e6-25d8-4b86-9362-b95ea79fa7fc   10Gi       RWX            Delete           Bound    grant/ebs-rwx-pvc                           openebs-rwx`
6. `kubectl get po | grep busybox` ---> Find the following: `busybox-76cbb94474-bq4dr                    0/2     Init:0/1   0          24m`
7. `kubectl describe deploy busybox`. Find the following output:
```
Mounts:
      /mnt/otp-shared-data from nfs-volume (rw)
  Volumes:
   nfs-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  ebs-rwx-pvc
    ReadOnly:   false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      False   MinimumReplicasUnavailable
  Progressing    False   ProgressDeadlineExceeded
OldReplicaSets:  <none>
NewReplicaSet:   busybox-76cbb94474 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  26m   deployment-controller  Scaled up replica set busybox-76cbb94474 to 1
```
8. `kubectl describe rs busybox`. Find the following log:
```
Environment:  <none>
    Mounts:
      /mnt/otp-shared-data from nfs-volume (rw)
  Volumes:
   nfs-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  ebs-rwx-pvc
    ReadOnly:   false
Events:
  Type    Reason            Age   From                   Message
  ----    ------            ----  ----                   -------
  Normal  SuccessfulCreate  27m   replicaset-controller  Created pod: busybox-76cbb94474-bq4dr
```

So, as we see. Container is created and the nfs volume is provisioned. However, the container fails to boot

**The output of the following commands will help us better understand what's going on**:

* `kubectl get pods -n <openebs_namespace> --show-labels`
* `kubectl logs <upgrade_job_pod> -n <openebs_namespace>`

**Anything else we need to know?:**

**Environment details:**
- OpenEBS version (use `kubectl get po -n openebs --show-labels`):
```
NAME                                                            READY   STATUS    RESTARTS   AGE   LABELS
nfs-pvc-505263e6-25d8-4b86-9362-b95ea79fa7fc-6b6f5df896-7spqf   0/1     Pending   0          48m   openebs.io/nfs-server=nfs-pvc-505263e6-25d8-4b86-9362-b95ea79fa7fc,pod-template-hash=6b6f5df896
openebs-localpv-provisioner-66b6b855fc-km4nb                    1/1     Running   4          18d   name=openebs-localpv-provisioner,openebs.io/component-name=openebs-localpv-provisioner,openebs.io/version=2.6.0,pod-template-hash=66b6b855fc
openebs-ndm-6xzkm                                               1/1     Running   8          18d   controller-revision-hash=7994455ddf,name=openebs-ndm,openebs.io/component-name=ndm,openebs.io/version=2.6.0,pod-template-generation=1
openebs-ndm-lv7kb                                               1/1     Running   0          17d   controller-revision-hash=7994455ddf,name=openebs-ndm,openebs.io/component-name=ndm,openebs.io/version=2.6.0,pod-template-generation=1
openebs-ndm-operator-6bd5949967-kx6wd                           1/1     Running   4          18d   name=openebs-ndm-operator,openebs.io/component-name=ndm-operator,openebs.io/version=2.6.0,pod-template-hash=6bd5949967
openebs-nfs-provisioner-7b4c9b87d9-2b9lb                        1/1     Running   0          24h   name=openebs-nfs-provisioner,openebs.io/component-name=openebs-nfs-provisioner,openebs.io/version=dev,pod-template-hash=7b4c9b87d9
```
- Kubernetes version (use `kubectl version`):
Client Version: v1.20.4
Server Version: v1.20.4
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
Ubuntu Server 20.04.2
- kernel (e.g: `uname -a`):
Linux grant-02 5.4.0-66-generic
- others:
`kubectl describe deploy nfs-pvc -n openebs` yields the following:
```
Pod Template:
  Labels:  openebs.io/nfs-server=nfs-pvc-505263e6-25d8-4b86-9362-b95ea79fa7fc
  Containers:
   nfs-server:
    Image:       itsthenetwork/nfs-server-alpine
    Ports:       2049/TCP, 111/TCP
    Host Ports:  0/TCP, 0/TCP
    Environment:
      SHARED_DIRECTORY:  /nfsshare
    Mounts:
      /nfsshare from exports-dir (rw)
  Volumes:
   exports-dir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  nfs-pvc-505263e6-25d8-4b86-9362-b95ea79fa7fc
    ReadOnly:   false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      False   MinimumReplicasUnavailable
  Progressing    False   ProgressDeadlineExceeded
OldReplicaSets:  <none>
NewReplicaSet:   nfs-pvc-505263e6-25d8-4b86-9362-b95ea79fa7fc-6b6f5df896 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  51m   deployment-controller  Scaled up replica set nfs-pvc-505263e6-25d8-4b86-9362-b95ea79fa7fc-6b6f5df896 to 1
```

**Comment by tampler** [comment]
I was able to detect the issues. This happens due to the lack of NFS pre-configuration itself. I need to create a `/nfsshare` folder and setup/validate a NFS service properly before apply.

This is a big issues with documentation, since no info is available with pre-requesties

**Comment by watcher00090** [comment]
@tampler Thanks for posting this issue as well as providing the various troubleshooting outputs. 

What was the default storageClass in the cluster when you tried to create the NFS provisioner? If you run `kubectl get sc`, it should tell you which storage class is the default.

**Comment by tampler** [comment]
After poking for a week with this issue, I've switched to [this](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner) project and was happily able to dynamically provision NFS for my services. Now having this:
```
NAME               PROVISIONER                                     RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
nfs-client         cluster.local/nfs-subdir-external-provisioner   Delete          Immediate              true                   4d
```
However, if you want me to debug this, I'll try with your project and supply a feedback. If anyone wants to do that and write some documentation
