### ISSUE TITLE
BDD test 'TEST PROVISIONING WITH DIFFERENT TOPOLOGY FOR BACKEND SC' fails

### ISSUE THREAD

**Issue by Abhinandan-Purkait** [openebs-archive/dynamic-nfs-provisioner#175]
This test uses `NodeAffinityLabel` in hostpath-provisioner. This CAS Config key is deprecated, needs to be updated.

**Comment by dsharma-dc** [comment]
Can this be closed?

**Comment by dsharma-dc** [comment]
Closing as the associated PR is merged.
