### ISSUE TITLE
Supporting arm64-architecture

### ISSUE THREAD

**Issue by logi85** [openebs-archive/dynamic-nfs-provisioner#18]
**Describe the problem/challenge you have**
Currently, a nfs-server-image (itsthenetwork/nfs-server-alpine, provisioner/helper_kernel_nfs_server.go ) is used, which is only available for amd64 at latest tag. 

**Describe the solution you'd like**
I think the best solution would be to use a Image with arm64-support. I solved this issue locally by building the used image for amd64 + arm64 (i'm using a mixed setup) and pushed it to the kubernetes-registry. Then I changed the deployment-yaml using this image instead.
Used build-command: docker buildx build --platform linux/amd64,linux/arm64 -t [REGISTRY_IP]:32000/itsthenetwork/nfs-server-alpine:latest --push .
The second solution would be imho to make it configurable which image is used.
Info: With this changes it is possible to mount a pv.

**Environment:**
- OpenEBS version (use `kubectl get po -n openebs --show-labels`): 2.7.0
- Kubernetes version (use `kubectl version`): v1.20.4-34+1ae8c29bbb48f7 (microk8s)
- Cloud provider or hardware configuration: rock64, raspberry pi (4), intel nuc 5i3
- OS (e.g: `cat /etc/os-release`): 3x Ubuntu 20.04
- kernel (e.g: `uname -a`): Linux nuc 5.4.0-70-generic, Linux rock64 5.10.21-rockchip64, Linux pi4 5.4.0-1032-raspi
- others: using jiva as backend

**Comment by rahulkrishnanfs** [comment]
@logi85 Thanks for posting this issue. We are working on it to add the support for arm64

**Comment by kmova** [comment]
Both the solutions need to be implemented. 

(a) Use a multi-arch image that supports both arm and amd64. This will be useful for clusters that have both arm and amd64 nodes. 

(b) Make the image name configurable. This will be useful for air-gapped clusters that will not be able to download the default image from the public internet.

**Comment by mynktl** [comment]
Closing this issue since multi-arch image changes are merged. Link for PR https://github.com/openebs/dynamic-nfs-provisioner/pull/26
Above PR has added support for the following architecture:
- linux/amd64
- linux/arm64
- linux/arm/v7
- linux/ppc64le
