### ISSUE TITLE
NFS Provisioner - GitHub updates

### ISSUE THREAD

**Issue by kmova** [openebs-archive/dynamic-nfs-provisioner#24]
- [x] README Updates 
  - [x] Badges
  - [x] Project Status - Beta
  - [x] k8s version compatibility
  - [x] Quickstart guide 
  - [x] Contributor Docs
  - [x] Adopters.md with links to openebs/openebs adopters
  - [x] Roadmap link to openebs project
  - [x] Community Links 
- [x] Helm Charts
- [x] GitHub Builds
- [x] Multiarch builds
- [x] Disable Travis
- [x] Downstream tagging
- [x] e2e tests
- [x] Upgrades
- [x] Monitoring
- [x] Troubleshooting guide

**Comment by mittachaitu** [comment]
Here are the document links:
- [Link](https://github.com/openebs/dynamic-nfs-provisioner/blob/develop/docs/troubleshooting.md) to troubleshooting doc in the repo.
- Initial dropout for [e2e tests](https://github.com/openebs/dynamic-nfs-provisioner/tree/develop/e2e-tests#e2e-tests) was added into the repo.
So tick marking both

**Comment by mynktl** [comment]
[PR](https://github.com/openebs/dynamic-nfs-provisioner/pull/123) for upgrade document
