### ISSUE TITLE
Helm chart issues

### ISSUE THREAD

**Issue by Atharex** [openebs-archive/dynamic-nfs-provisioner#38]
There are a few bugs with the helm chart in need of fixing.

1. The liveness probe is wrongly configured and the NFS pod keeps continuously restarting. (https://github.com/openebs/dynamic-nfs-provisioner/blob/develop/deploy/helm/charts/templates/deployment.yaml#L93) The pgrep command seems to have the wrong version and does not have the `-c` option. Therefore it keeps crashing and failing the liveness probe

2. The PSP config does not work because of a typo (https://github.com/openebs/dynamic-nfs-provisioner/blob/develop/deploy/helm/charts/templates/clusterrole.yaml#L40)  - there is `}}}` instead of `<space>}}`

**Comment by kmova** [comment]
Hi @Atharex -- thank you for catching the above errors. Would you like to raise a PR to fix the above?

**Comment by Atharex** [comment]
Sure. Here's my pull request @kmova
