### ISSUE TITLE
Missing write permission for the storage class of the NFS provisioner

### ISSUE THREAD

**Issue by Atharex** [openebs-archive/dynamic-nfs-provisioner#39]
Hi,

I've installed the NFS provisioner helm chart and it starts up correctly. On top of it I try to install Minio with an RWX storage class from the provisioner. The PVCs & PVs seem to be correctly provisioned, but Minio will not start because of a permission error:

```
ERROR Unable to initialize backend: Unable to write to the backend
      > Please ensure MinIO binary has write permissions for the backend
      HINT:
        Run the following command to add write permissions: `sudo chown -R <your-username> /export && sudo chmod u+rxw /export`
```

I use the default helm chart values, where I remove the liveness check and set the nfsStorageClass.backendStorageClass to an existing cStor-based storage class of my Open EBS installation. I also install the PSP components.

If I install minio on the OpenEBS cStor-based RWO storage class, it works normally, but it fails with missing write permission when I use the storage class of this provisioner.

Is there a configuration when installing NFS provisioner that I am missing to solve this error?

**Comment by mynktl** [comment]
Hi @Atharex, 
you might be facing this issue because of the security context. Minio deployment is having this set to
```
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
```
and volume is having some default directory with user root. To solve this issue, you can remove this security context in minio deployment or need to clean the directory manually.

**Comment by Atharex** [comment]
That was indeed the issue @mynktl thanks!
