### ISSUE TITLE
Keeping helm values in sync with the tagged release

### ISSUE THREAD

**Issue by kmova** [openebs-archive/dynamic-nfs-provisioner#88]
Keeping helm values in sync with the tagged release 

Just an observation that if we club the code and helm chart changes, the helm chart ends up having a configurable value that is not yet available in the released version. This will need to be addressed once we hit beta by either adding a column that specifies the version from which the value will be available or indicating that a given value will be available in the next tagged release.

_Originally posted by @kmova in https://github.com/openebs/dynamic-nfs-provisioner/pull/84#r688246398_

**Comment by mynktl** [comment]
To solve this, we will [add an option in the PR Template](https://github.com/openebs/dynamic-nfs-provisioner/pull/94) to know if PR requires changes in the helm chart and, PR number for the relevant helm chart changes. This PRs will get merged once the release tag is created, provided relevant changes are available in the image.

Label `release-activity` should be added on both implementation and helm chart PR for filtering.
